In [2]:
import pandas as pd

In [36]:
df_path = "C:/Users/AyoubJELLOULI/Desktop/HETIC/Projet_RNCP/git_repos/SAVAI-BACK/free_tweet_export.csv"
df = pd.read_csv(df_path)
df.head()

,id,created_at,full_text,media,screen_name,name,profile_image_url,user_id,in_reply_to,retweeted_status,...,favorite_count,retweet_count,bookmark_count,quote_count,reply_count,views_count,favorited,retweeted,bookmarked,url
0,1343458257915031553,2020-12-28 08:26:23 +01:00,"💩 à @free parce-que Débit Très instable, … \n\...",[],m_annuel,M Annuel,https://abs.twimg.com/sticky/default_profile_i...,1104790986801250304,NaN,NaN,...,2,1,0,0,1,NaN,False,False,False,https://twitter.com/m_annuel/status/1343458257...
1,1393158240083587075,2021-05-14 12:56:22 +02:00,"RT @free: Retrouvez désormais @ToonamiFR, la c...","[{""type"":""photo"",""url"":""https://t.co/kuAYafYDi...",Freebox,Assistance Freebox,https://pbs.twimg.com/profile_images/671676021...,58920430,NaN,1.393125e+18,...,0,16,0,0,0,NaN,False,False,False,https://twitter.com/Freebox/status/13931582400...
2,1403337211475546112,2021-06-11 15:03:58 +02:00,"RT @free: A suivre ce soir, le 1er match de l’...","[{""type"":""photo"",""url"":""https://t.co/gMTcYtGdd...",Freebox,Assistance Freebox,https://pbs.twimg.com/profile_images/671676021...,58920430,NaN,1.403329e+18,...,0,15,0,0,0,NaN,False,False,False,https://twitter.com/Freebox/status/14033372114...
3,1403337257571004417,2021-06-11 15:04:09 +02:00,RT @free: Disponible sur le canal 101 avec les...,[],Freebox,Assistance Freebox,https://pbs.twimg.com/profile_images/671676021...,58920430,NaN,1.403333e+18,...,0,5,0,0,0,NaN,False,False,False,https://twitter.com/Freebox/status/14033372575...
4,1418550491034882052,2021-07-23 14:36:07 +02:00,« Faites vos premiers pas avec nous ! Découvre...,"[{""type"":""video"",""url"":""https://t.co/YCMv79evb...",Freebox,Assistance Freebox,https://pbs.twimg.com/profile_images/671676021...,58920430,NaN,NaN,...,31,7,0,3,35,NaN,False,False,False,https://twitter.com/Freebox/status/14185504910...

In [37]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6375 entries, 0 to 6374
Data columns (total 22 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 6375 non-null   int64
 1   created_at         6375 non-null   object
 2   full_text          6375 non-null   object
 3   media              6375 non-null   object
 4   screen_name        6375 non-null   object
 5   name               6375 non-null   object
 6   profile_image_url  6375 non-null   object
 7   user_id            6375 non-null   int64
 8   in_reply_to        3887 non-null   float64
 9   retweeted_status   16 non-null     float64
 10  quoted_status      103 non-null    float64
 11  media_tags         6375 non-null   object
 12  favorite_count     6375 non-null   int64
 13  retweet_count      6375 non-null   int64
 14  bookmark_count     6375 non-null   int64
 15  quote_count        6375 non-null   int64
 16  reply_count        6375 non-null   int64
 17  views_count        6346 non-null   float64
 18  favorited          6375 non-null   bool
 19  retweeted          6375 non-null   bool
 20  bookmarked         6375 non-null   bool
 21  url                6375 non-null   object
dtypes: bool(3), float64(4), int64(7), object(8)
memory usage: 965.1+ KB

In [38]:
# Sélectionner uniquement les colonnes souhaitées
df = df[["id", "created_at", "full_text", "screen_name", "name", "user_id", "in_reply_to", "retweeted"]].copy()
df

,id,created_at,full_text,screen_name,name,user_id,in_reply_to,retweeted
0,1343458257915031553,2020-12-28 08:26:23 +01:00,"💩 à @free parce-que Débit Très instable, … \n\...",m_annuel,M Annuel,1104790986801250304,NaN,False
1,1393158240083587075,2021-05-14 12:56:22 +02:00,"RT @free: Retrouvez désormais @ToonamiFR, la c...",Freebox,Assistance Freebox,58920430,NaN,False
2,1403337211475546112,2021-06-11 15:03:58 +02:00,"RT @free: A suivre ce soir, le 1er match de l’...",Freebox,Assistance Freebox,58920430,NaN,False
3,1403337257571004417,2021-06-11 15:04:09 +02:00,RT @free: Disponible sur le canal 101 avec les...,Freebox,Assistance Freebox,58920430,NaN,False
4,1418550491034882052,2021-07-23 14:36:07 +02:00,« Faites vos premiers pas avec nous ! Découvre...,Freebox,Assistance Freebox,58920430,NaN,False
...,...,...,...,...,...,...,...,...
6370,1934890606209196214,2025-06-17 10:27:23 +02:00,"Bonjour @free , c'est bien long pour trouver u...",JMA38620,Jean-Marc,802241352,NaN,False
6371,1934892363941302503,2025-06-17 10:34:22 +02:00,"@maarylou_v Bonjour,\n\nLa messagerie privée X...",Freebox,Assistance Freebox,58920430,1.934651e+18,False
6372,1934907898917691817,2025-06-17 11:36:06 +02:00,"@iac_yac Bonjour,\n\nLa messagerie privée X n’...",Freebox,Assistance Freebox,58920430,1.934673e+18,False
6373,1934909296245887334,2025-06-17 11:41:39 +02:00,"@MartinVine52691 Bonjour,\n\nLa messagerie pri...",Freebox,Assistance Freebox,58920430,1.934690e+18,False
6374,1934914907591344259,2025-06-17 12:03:57 +02:00,"@JMA38620 Bonjour,\n\nLa messagerie privée X n...",Freebox,Assistance Freebox,58920430,1.934891e+18,False

In [39]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6375 entries, 0 to 6374
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   id           6375 non-null   int64
 1   created_at   6375 non-null   object
 2   full_text    6375 non-null   object
 3   screen_name  6375 non-null   object
 4   name         6375 non-null   object
 5   user_id      6375 non-null   int64
 6   in_reply_to  3887 non-null   float64
 7   retweeted    6375 non-null   bool
dtypes: bool(1), float64(1), int64(2), object(4)
memory usage: 355.0+ KB

In [41]:
df['created_at'] = pd.to_datetime(df['created_at'], utc=True)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6375 entries, 0 to 6374
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   id           6375 non-null   int64
 1   created_at   6375 non-null   datetime64[ns, UTC]
 2   full_text    6375 non-null   object
 3   screen_name  6375 non-null   object
 4   name         6375 non-null   object
 5   user_id      6375 non-null   int64
 6   in_reply_to  3887 non-null   float64
 7   retweeted    6375 non-null   bool
dtypes: bool(1), datetime64[ns, UTC](1), float64(1), int64(2), object(3)
memory usage: 355.0+ KB

In [42]:
df.head()

,id,created_at,full_text,screen_name,name,user_id,in_reply_to,retweeted
0,1343458257915031553,2020-12-28 07:26:23+00:00,"💩 à @free parce-que Débit Très instable, … \n\...",m_annuel,M Annuel,1104790986801250304,NaN,False
1,1393158240083587075,2021-05-14 10:56:22+00:00,"RT @free: Retrouvez désormais @ToonamiFR, la c...",Freebox,Assistance Freebox,58920430,NaN,False
2,1403337211475546112,2021-06-11 13:03:58+00:00,"RT @free: A suivre ce soir, le 1er match de l’...",Freebox,Assistance Freebox,58920430,NaN,False
3,1403337257571004417,2021-06-11 13:04:09+00:00,RT @free: Disponible sur le canal 101 avec les...,Freebox,Assistance Freebox,58920430,NaN,False
4,1418550491034882052,2021-07-23 12:36:07+00:00,« Faites vos premiers pas avec nous ! Découvre...,Freebox,Assistance Freebox,58920430,NaN,False

In [43]:
df['created_at_local'] = df['created_at'].dt.tz_convert('Europe/Paris')
df.head()

,id,created_at,full_text,screen_name,name,user_id,in_reply_to,retweeted,created_at_local
0,1343458257915031553,2020-12-28 07:26:23+00:00,"💩 à @free parce-que Débit Très instable, … \n\...",m_annuel,M Annuel,1104790986801250304,NaN,False,2020-12-28 08:26:23+01:00
1,1393158240083587075,2021-05-14 10:56:22+00:00,"RT @free: Retrouvez désormais @ToonamiFR, la c...",Freebox,Assistance Freebox,58920430,NaN,False,2021-05-14 12:56:22+02:00
2,1403337211475546112,2021-06-11 13:03:58+00:00,"RT @free: A suivre ce soir, le 1er match de l’...",Freebox,Assistance Freebox,58920430,NaN,False,2021-06-11 15:03:58+02:00
3,1403337257571004417,2021-06-11 13:04:09+00:00,RT @free: Disponible sur le canal 101 avec les...,Freebox,Assistance Freebox,58920430,NaN,False,2021-06-11 15:04:09+02:00
4,1418550491034882052,2021-07-23 12:36:07+00:00,« Faites vos premiers pas avec nous ! Découvre...,Freebox,Assistance Freebox,58920430,NaN,False,2021-07-23 14:36:07+02:00

In [44]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6375 entries, 0 to 6374
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   id                6375 non-null   int64
 1   created_at        6375 non-null   datetime64[ns, UTC]
 2   full_text         6375 non-null   object
 3   screen_name       6375 non-null   object
 4   name              6375 non-null   object
 5   user_id           6375 non-null   int64
 6   in_reply_to       3887 non-null   float64
 7   retweeted         6375 non-null   bool
 8   created_at_local  6375 non-null   datetime64[ns, Europe/Paris]
dtypes: bool(1), datetime64[ns, Europe/Paris](1), datetime64[ns, UTC](1), float64(1), int64(2), object(3)
memory usage: 404.8+ KB

In [ ]:
df['full_text'] = df['full_text'].astype('string')
df['screen_name'] = df['screen_name'].astype('string')
df['name'] = df['name'].astype('string')
df['user_id'] = df['user_id'].astype('Int64')
df['in_reply_to'] = df['in_reply_to'].astype('Int64')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6375 entries, 0 to 6374
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   id                6375 non-null   int64
 1   created_at        6375 non-null   datetime64[ns, UTC]
 2   full_text         6375 non-null   string
 3   screen_name       6375 non-null   string
 4   name              6375 non-null   string
 5   user_id           6375 non-null   Int64
 6   in_reply_to       3887 non-null   Int64
 7   retweeted         6375 non-null   bool
 8   created_at_local  6375 non-null   datetime64[ns, Europe/Paris]
dtypes: Int64(2), bool(1), datetime64[ns, Europe/Paris](1), datetime64[ns, UTC](1), int64(1), string(3)
memory usage: 417.2 KB

,id,created_at,full_text,screen_name,name,user_id,in_reply_to,retweeted,created_at_local
0,1343458257915031553,2020-12-28 07:26:23+00:00,"💩 à @free parce-que Débit Très instable, … \n\...",m_annuel,M Annuel,1104790986801250304,<NA>,False,2020-12-28 08:26:23+01:00
1,1393158240083587075,2021-05-14 10:56:22+00:00,"RT @free: Retrouvez désormais @ToonamiFR, la c...",Freebox,Assistance Freebox,58920430,<NA>,False,2021-05-14 12:56:22+02:00
2,1403337211475546112,2021-06-11 13:03:58+00:00,"RT @free: A suivre ce soir, le 1er match de l’...",Freebox,Assistance Freebox,58920430,<NA>,False,2021-06-11 15:03:58+02:00
3,1403337257571004417,2021-06-11 13:04:09+00:00,RT @free: Disponible sur le canal 101 avec les...,Freebox,Assistance Freebox,58920430,<NA>,False,2021-06-11 15:04:09+02:00
4,1418550491034882052,2021-07-23 12:36:07+00:00,« Faites vos premiers pas avec nous ! Découvre...,Freebox,Assistance Freebox,58920430,<NA>,False,2021-07-23 14:36:07+02:00

In [49]:
df.head()

,id,created_at,full_text,screen_name,name,user_id,in_reply_to,retweeted,created_at_local
0,1343458257915031553,2020-12-28 07:26:23+00:00,"💩 à @free parce-que Débit Très instable, … \n\...",m_annuel,M Annuel,1104790986801250304,<NA>,False,2020-12-28 08:26:23+01:00
1,1393158240083587075,2021-05-14 10:56:22+00:00,"RT @free: Retrouvez désormais @ToonamiFR, la c...",Freebox,Assistance Freebox,58920430,<NA>,False,2021-05-14 12:56:22+02:00
2,1403337211475546112,2021-06-11 13:03:58+00:00,"RT @free: A suivre ce soir, le 1er match de l’...",Freebox,Assistance Freebox,58920430,<NA>,False,2021-06-11 15:03:58+02:00
3,1403337257571004417,2021-06-11 13:04:09+00:00,RT @free: Disponible sur le canal 101 avec les...,Freebox,Assistance Freebox,58920430,<NA>,False,2021-06-11 15:04:09+02:00
4,1418550491034882052,2021-07-23 12:36:07+00:00,« Faites vos premiers pas avec nous ! Découvre...,Freebox,Assistance Freebox,58920430,<NA>,False,2021-07-23 14:36:07+02:00